name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull prawinpracash/omegle-clone:latest
    - name: Delete Old docker container
      run: sudo docker rm -f omegle-clone-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name omegle-clone-pipeline-container prawinpracash/omegle-clone:latest