name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Deployment

    steps:
    - uses: actions/checkout@v4
    - name: Docker hub login
      env:
        DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t omegle-clone ./server
    - name: Push docker image
      run: docker push prawinpracash/omgele-clone:latest
                       
